import UIKit

final class PlayerViewController: UIViewController {
    private let artwork = UIImageView(); private let titleLabel = UILabel(); private let artistLabel = UILabel(); private let slider = UISlider(); private let timeLabel = UILabel(); private let durationLabel = UILabel(); private let playButton = UIButton(type: .system); private let shuffleButton = UIButton(type: .system); private let repeatButton = UIButton(type: .system); private let manager = MusicPlayerManager.shared
    override func viewDidLoad() { super.viewDidLoad(); title = "Now Playing"; view.backgroundColor = .white; [artwork, titleLabel, artistLabel, slider, timeLabel, durationLabel, playButton, shuffleButton, repeatButton].forEach { view.addSubview($0) }; artwork.contentMode = .scaleAspectFit; artwork.backgroundColor = UIColor(white: 0.92, alpha: 1); titleLabel.textAlignment = .center; artistLabel.textAlignment = .center; playButton.setTitle("Play/Pause", for: .normal); shuffleButton.setTitle("Shuffle", for: .normal); repeatButton.setTitle("Repeat", for: .normal); playButton.addTarget(self, action: #selector(toggle), for: .touchUpInside); shuffleButton.addTarget(self, action: #selector(shuffle), for: .touchUpInside); repeatButton.addTarget(self, action: #selector(repeatMode), for: .touchUpInside); slider.addTarget(self, action: #selector(seek), for: .valueChanged); manager.onChange = { [weak self] in self?.refresh() }; refresh() }
    override func viewDidLayoutSubviews() { let w = view.bounds.width; artwork.frame = CGRect(x: 24, y: 90, width: w - 48, height: w - 48); titleLabel.frame = CGRect(x: 16, y: artwork.frame.maxY + 18, width: w - 32, height: 28); artistLabel.frame = CGRect(x: 16, y: titleLabel.frame.maxY, width: w - 32, height: 22); slider.frame = CGRect(x: 20, y: artistLabel.frame.maxY + 22, width: w - 40, height: 30); timeLabel.frame = CGRect(x: 20, y: slider.frame.maxY, width: 80, height: 22); durationLabel.frame = CGRect(x: w - 100, y: slider.frame.maxY, width: 80, height: 22); playButton.frame = CGRect(x: w/2 - 55, y: slider.frame.maxY + 45, width: 110, height: 44); shuffleButton.frame = CGRect(x: 20, y: playButton.frame.minY, width: 90, height: 44); repeatButton.frame = CGRect(x: w - 110, y: playButton.frame.minY, width: 90, height: 44) }
    private func refresh() { guard let song = manager.currentSong else { return }; titleLabel.text = song.title; artistLabel.text = song.artist; durationLabel.text = format(song.duration); timeLabel.text = format(manager.player.currentTime().seconds); slider.maximumValue = Float(max(song.duration, 1)); slider.value = Float(min(max(manager.player.currentTime().seconds, 0), song.duration)); artwork.image = song.artworkData.flatMap { UIImage(data: $0) }; shuffleButton.alpha = manager.shuffle ? 1 : 0.5; repeatButton.setTitle(["Repeat Off", "Repeat One", "Repeat All"][manager.repeatMode.rawValue], for: .normal) }
    @objc private func toggle() { manager.toggle() }; @objc private func seek() { manager.seek(to: TimeInterval(slider.value)) }; @objc private func shuffle() { manager.shuffle.toggle(); refresh() }; @objc private func repeatMode() { manager.repeatMode = RepeatMode(rawValue: (manager.repeatMode.rawValue + 1) % 3) ?? .off; refresh() }
    private func format(_ seconds: TimeInterval) -> String { String(format: "%d:%02d", max(0, Int(seconds)) / 60, max(0, Int(seconds)) % 60) }
}
