import UIKit

final class ViewController: UIViewController, UITableViewDataSource, UITableViewDelegate, UIDocumentPickerDelegate {
    private let tableView = UITableView(frame: .zero, style: .plain); private let miniTitle = UILabel(); private let miniPlay = UIButton(type: .system); private let library = MusicLibraryManager.shared
    override func viewDidLoad() { super.viewDidLoad(); title = "Offline Music"; view.backgroundColor = .white; navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(importAudio)); tableView.dataSource = self; tableView.delegate = self; tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell"); view.addSubview(tableView); miniTitle.text = "No song selected"; miniTitle.font = .systemFont(ofSize: 13); miniPlay.setTitle("Play", for: .normal); miniPlay.addTarget(self, action: #selector(toggle), for: .touchUpInside); view.addSubview(miniTitle); view.addSubview(miniPlay); MusicPlayerManager.shared.onChange = { [weak self] in self?.refreshMini() }; refreshMini() }
    override func viewDidLayoutSubviews() { super.viewDidLayoutSubviews(); let h: CGFloat = 52; miniTitle.frame = CGRect(x: 12, y: view.bounds.height - h, width: view.bounds.width - 90, height: h); miniPlay.frame = CGRect(x: view.bounds.width - 78, y: view.bounds.height - h, width: 70, height: h); tableView.frame = CGRect(x: 0, y: 0, width: view.bounds.width, height: view.bounds.height - h) }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int { library.songs.count }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell { let cell = UITableViewCell(style: .subtitle, reuseIdentifier: "Cell"); let song = library.songs[indexPath.row]; cell.textLabel?.text = song.title; cell.detailTextLabel?.text = "\(song.artist) • \(format(song.duration))"; if let data = song.artworkData { cell.imageView?.image = UIImage(data: data) }; return cell }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) { MusicPlayerManager.shared.play(library.songs[indexPath.row]); navigationController?.pushViewController(PlayerViewController(), animated: true) }
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) { if editingStyle == .delete { try? library.delete(library.songs[indexPath.row]); tableView.deleteRows(at: [indexPath], with: .automatic) } }
    @objc private func importAudio() { let picker = UIDocumentPickerViewController(documentTypes: ["public.mp3", "public.audio", "com.apple.m4a-audio", "com.microsoft.waveform-audio"], in: .import); picker.delegate = self; picker.allowsMultipleSelection = true; present(picker, animated: true) }
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) { urls.forEach { try? library.importFile(at: $0) }; tableView.reloadData() }
    @objc private func toggle() { MusicPlayerManager.shared.toggle() }
    private func refreshMini() { miniTitle.text = MusicPlayerManager.shared.currentSong?.title ?? "No song selected"; miniPlay.setTitle(MusicPlayerManager.shared.player.rate > 0 ? "Pause" : "Play", for: .normal) }
    private func format(_ seconds: TimeInterval) -> String { String(format: "%d:%02d", Int(seconds) / 60, Int(seconds) % 60) }
}
